#include "src/_main.h"
//---------------------------------
#include "src/RestoreIPAddress.cpp"
//#include "src/Permutations.cpp"
//#include "src/SubsetsII.cpp"
//#include "src/PriorityQueue.cpp"
//#include "src/std_move.cpp"
//#include "src/StringView.cpp"
//#include "src/TappingRainWater.cpp"
//#include "src/usageOfdeclspec.cpp"
//#include "src/LC81SearchInRotatedSortedArrayII.cpp"
//#include "src/LC153_FindMinRotatedArray.cpp"
//#include "src/LC33.cpp"
//#include "src/SharedPointers.cpp"
//#include "src/SmartPointers.cpp"
//#include "src/ReferenceAndPointer.cpp"
//#include "src/StaticConcepts.cpp"
//#include "src/ArraysVectors.cpp"
//#include "src/Lambda.cpp"
//#include "src/VirtualFunctions.cpp"
//#include "src/Destructors.cpp"
//#include "src/MoveConstructor.cpp"
//#include "src/Threading_01.cpp"
//#include "src/Threading_02.cpp"
//#include "src/NoExcept_01.cpp"
//#include "src/Template_01.cpp"
//#include "src/LValueRValue.cpp"
//#include "src/Alignment.cpp"
//#include "src/Threading_03.cpp"
//#include "src/Casting.cpp"
//#include "src/Attributes.cpp"

// Run whatever you want
RUN(RestoreIPAddress::Solution);
